# Generated by Django 5.0.2 on 2024-03-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_professor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
