# Generated by Django 5.0.2 on 2024-03-04 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0003_alter_professor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateField()),
                ('almoco', models.DateField()),
                ('retorno_almoco', models.DateField()),
                ('saida_expediente', models.DateField()),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='professor', to='professor.professor')),
            ],
        ),
    ]
