# Generated by Django 5.0.2 on 2024-03-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervalo', '0002_alter_intervalo_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalo',
            name='almoco',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='intervalo',
            name='entrada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='intervalo',
            name='retorno_almoco',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='intervalo',
            name='saida_expediente',
            field=models.DateTimeField(),
        ),
    ]
