# Generated by Django 5.0.2 on 2024-03-05 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervalo', '0003_alter_intervalo_almoco_alter_intervalo_entrada_and_more'),
        ('professor', '0003_alter_professor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalo',
            name='professor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='professor.professor'),
        ),
    ]
