# Generated by Django 5.0.2 on 2024-03-05 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervalo', '0004_alter_intervalo_professor'),
        ('professor', '0003_alter_professor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervalo',
            name='email',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='professor.professor'),
        ),
    ]
