# Generated by Django 5.0.2 on 2024-03-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervalo', '0006_alter_intervalo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
