# Generated by Django 5.0.2 on 2024-03-05 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intervalo', '0008_alter_intervalo_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervalo',
            name='email',
        ),
    ]
