# Generated by Django 5.0.2 on 2024-03-06 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervalo', '0009_remove_intervalo_email'),
        ('professor', '0003_alter_professor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalo',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='professor.professor'),
        ),
    ]
