# Generated by Django 5.0.2 on 2024-03-06 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervalo', '0010_alter_intervalo_professor'),
        ('professor', '0003_alter_professor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalo',
            name='professor',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='professor.professor'),
            preserve_default=False,
        ),
    ]
