# Generated by Django 5.0.2 on 2024-03-09 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliar', '0001_initial'),
        ('intervalo', '0011_alter_intervalo_professor'),
        ('professor', '0003_alter_professor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervalo',
            name='auxiliar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auxiliar.auxiliar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intervalo',
            name='professor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='professor.professor'),
        ),
    ]
