# Generated by Django 5.0.2 on 2024-03-09 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliar', '0001_initial'),
        ('intervalo', '0013_alter_intervalo_auxiliar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalo',
            name='auxiliar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='auxiliar', to='auxiliar.auxiliar'),
        ),
    ]
