# Generated by Django 5.0.2 on 2024-03-09 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliar', '0001_initial'),
        ('intervalo', '0016_alter_intervalo_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalo',
            name='auxiliar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervalos', to='auxiliar.auxiliar'),
        ),
    ]
