# Generated by Django 5.0.2 on 2024-03-16 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intervalo', '0019_alter_intervalo_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='intervalo',
            unique_together=set(),
        ),
    ]
